import { StrictMode, type ReactNode } from "react";
import { act, renderHook } from "@testing-library/react";
import { afterEach, describe, expect, it, vi } from "vitest";
import {
  DiffieHellmanGatewayError,
  type DiffieHellmanGateway,
} from "../services/diffieHellmanGateway";
import {
  createDeferred,
  createDiffieHellmanGateway,
  type DhFakeOptions,
} from "../test/createDiffieHellmanGateway";
import { createDhPresetResult, createDhRandomValues } from "../test/fixtures";
import type { DhTask } from "../types/cipher";
import { useDiffieHellman } from "./useDiffieHellman";

const preset = { q: "23", alpha: "5", privateA: "6", privateB: "15" };
const empty = { q: "", alpha: "", privateA: "", privateB: "" };
const tasks: DhTask[] = ["exchange", "random"];
const wrapper = ({ children }: { children: ReactNode }) => <StrictMode>{children}</StrictMode>;

function setup(options: DhFakeOptions = {}, withExample = true) {
  const gateway = createDiffieHellmanGateway(options);
  const initialProps: { gateway: DiffieHellmanGateway | null; active: boolean } = {
    gateway,
    active: true,
  };
  const hook = renderHook(
    ({ gateway, active }: { gateway: DiffieHellmanGateway | null; active: boolean }) =>
      useDiffieHellman(gateway, active),
    { initialProps, wrapper },
  );
  if (withExample) act(() => hook.result.current.loadExample());
  return { ...hook, gateway };
}

function invoke(controller: ReturnType<typeof useDiffieHellman>, task: DhTask) {
  return task === "exchange" ? controller.exchange() : controller.generatePrivateValues();
}

afterEach(() => vi.useRealTimers());

describe("Diffie–Hellman state controller", () => {
  it("starts empty and loads the preset only on request and never auto-runs under StrictMode", () => {
    const { result, gateway } = setup({}, false);
    expect(result.current).toMatchObject({
      draft: empty,
      status: "idle",
      task: null,
      snapshot: null,
      result: null,
      error: null,
      fieldErrors: {},
      isBusy: false,
    });
    act(() => result.current.loadExample());
    expect(result.current.draft).toEqual(preset);
    act(() => result.current.resetAll());
    expect(result.current.draft).toEqual(empty);
    expect(gateway.exchange).not.toHaveBeenCalled();
    expect(gateway.generatePrivateValues).not.toHaveBeenCalled();
    expect(result.current.resetVersion).toBe(2);
  });

  it("captures a normalized success snapshot while preserving the raw draft", async () => {
    const { result, gateway } = setup();
    act(() => result.current.setParameter("q", " \t00023\n"));
    await act(async () => {
      await result.current.exchange();
    });
    expect(gateway.exchange).toHaveBeenCalledWith(preset, expect.any(AbortSignal));
    expect(result.current).toMatchObject({
      status: "success",
      task: "exchange",
      draft: { ...preset, q: " \t00023\n" },
      snapshot: preset,
      result: createDhPresetResult(),
      isBusy: false,
    });
    act(() => result.current.setParameter("privateA", "7"));
    expect(result.current).toMatchObject({
      status: "idle",
      snapshot: null,
      result: null,
      error: null,
    });
  });

  it("omits blank private keys and snapshots the keys generated by Backend", async () => {
    const { result, gateway } = setup();
    act(() => {
      result.current.setParameter("privateA", " ");
      result.current.setParameter("privateB", "");
    });
    await act(async () => {
      await result.current.exchange();
    });
    expect(gateway.exchange).toHaveBeenCalledWith({ q: "23", alpha: "5" }, expect.any(AbortSignal));
    expect(result.current.snapshot).toEqual(preset);
    expect(result.current.draft).toEqual({ ...preset, privateA: " ", privateB: "" });
    expect(result.current.status).toBe("success");
  });

  it("reads the latest draft even when edit and submit occur in the same event", async () => {
    const { result, gateway } = setup();
    await act(async () => {
      result.current.setParameter("privateA", "15");
      result.current.setParameter("privateB", "6");
      await result.current.exchange();
    });
    expect(gateway.exchange.mock.calls[0][0]).toMatchObject({ privateA: "15", privateB: "6" });
    expect(result.current.result).toMatchObject({ publicA: "19", publicB: "8" });
  });

  it("replaces both random values together without generating an exchange result", async () => {
    const { result, gateway } = setup();
    await act(async () => {
      await result.current.exchange();
    });
    act(() => {
      result.current.setParameter("privateA", "invalid");
      result.current.setParameter("privateB", "");
    });
    await act(async () => {
      await result.current.generatePrivateValues();
    });
    expect(gateway.generatePrivateValues).toHaveBeenCalledExactlyOnceWith(
      { q: "23", alpha: "5" },
      expect.any(AbortSignal),
    );
    expect(result.current).toMatchObject({
      draft: createDhRandomValues(),
      status: "success",
      task: "random",
      snapshot: null,
      result: null,
    });
    expect(gateway.exchange).toHaveBeenCalledTimes(1);
  });

  it.each([
    ["", "Giá trị phải là chuỗi số nguyên không âm."],
    ["2.5", "Giá trị phải là chuỗi số nguyên không âm."],
    ["1e3", "Giá trị phải là chuỗi số nguyên không âm."],
    ["-6", "Giá trị phải là chuỗi số nguyên không âm."],
    ["２３", "Giá trị phải là chuỗi số nguyên không âm."],
    ["\u00a023\u00a0", "Giá trị phải là chuỗi số nguyên không âm."],
    ["1".repeat(40), "Giá trị không được vượt quá 39 chữ số."],
  ])("rejects bad format %j without a request", async (value, message) => {
    const { result, gateway } = setup();
    act(() => result.current.setParameter("q", value));
    await act(async () => {
      await result.current.exchange();
    });
    expect(result.current).toMatchObject({
      status: "error",
      error: message,
      fieldErrors: { q: message },
    });
    expect(gateway.exchange).not.toHaveBeenCalled();
  });

  it("reports the first format error and leaves numeric validation to Backend", async () => {
    const failure = new DiffieHellmanGatewayError("q không nguyên tố.", "NOT_PRIME", "q");
    const { result, gateway } = setup({ exchange: [{ kind: "error", error: failure }] });
    act(() => {
      result.current.setParameter("q", "21");
      result.current.setParameter("privateA", "x");
      result.current.setParameter("privateB", "x");
    });
    await act(async () => {
      await result.current.exchange();
    });
    expect(Object.keys(result.current.fieldErrors)).toEqual(["privateA"]);
    expect(gateway.exchange).not.toHaveBeenCalled();
    act(() => {
      result.current.setParameter("privateA", "6");
      result.current.setParameter("privateB", "15");
    });
    await act(async () => {
      await result.current.exchange();
    });
    expect(gateway.exchange).toHaveBeenCalledOnce();
    expect(result.current.fieldErrors).toEqual({ q: "q không nguyên tố." });
  });

  it.each(tasks)("blocks double submit and overlap while %s is pending", async (task) => {
    const deferred = createDeferred<unknown>();
    const { result, gateway } = setup({ [task]: [{ kind: "late", response: deferred.promise }] });
    let pending!: Promise<void>;
    act(() => {
      pending = invoke(result.current, task);
    });
    expect(result.current).toMatchObject({ status: "loading", task, isBusy: true, snapshot: null });
    await act(async () => {
      await result.current.exchange();
      await result.current.generatePrivateValues();
    });
    expect(
      gateway.exchange.mock.calls.length + gateway.generatePrivateValues.mock.calls.length,
    ).toBe(1);
    await act(async () => {
      deferred.resolve(task === "exchange" ? createDhPresetResult() : createDhRandomValues());
      await pending;
    });
    expect(result.current.status).toBe("success");
  });

  it.each(tasks)(
    "discards a late %s result after editing and does not unlock a newer request",
    async (task) => {
      const old = createDeferred<unknown>();
      const newer = createDeferred<unknown>();
      const { result, gateway } = setup({
        [task]: [
          { kind: "late", response: old.promise },
          { kind: "late", response: newer.promise },
        ],
      });
      let oldRun!: Promise<void>;
      act(() => {
        oldRun = invoke(result.current, task);
      });
      const abortSignal =
        task === "exchange"
          ? gateway.exchange.mock.calls[0][1]
          : gateway.generatePrivateValues.mock.calls[0][1];
      act(() => result.current.setParameter("privateA", "6"));
      expect(abortSignal.aborted).toBe(true);
      let newRun!: Promise<void>;
      act(() => {
        newRun = invoke(result.current, task);
      });
      await act(async () => {
        old.resolve(task === "exchange" ? createDhPresetResult() : createDhRandomValues());
        await oldRun;
        await Promise.resolve();
      });
      expect(result.current).toMatchObject({
        status: "loading",
        task,
        result: null,
        error: null,
        draft: preset,
      });
      await act(async () => {
        await invoke(result.current, task);
      });
      expect(
        gateway.exchange.mock.calls.length + gateway.generatePrivateValues.mock.calls.length,
      ).toBe(2);
      await act(async () => {
        newer.resolve(task === "exchange" ? createDhPresetResult() : createDhRandomValues());
        await newRun;
      });
      expect(result.current.status).toBe("success");
    },
  );

  it("drops a late error after reset and keeps a newer success", async () => {
    const deferred = createDeferred<unknown>();
    const { result } = setup({ exchange: [{ kind: "late", response: deferred.promise }] });
    let pending!: Promise<void>;
    act(() => {
      pending = result.current.exchange();
    });
    act(() => result.current.resetAll());
    act(() => result.current.loadExample());
    await act(async () => {
      await result.current.exchange();
    });
    await act(async () => {
      deferred.reject(new DiffieHellmanGatewayError("old failure", "INVALID_REQUEST", "q"));
      await pending;
      await Promise.resolve();
    });
    expect(result.current).toMatchObject({
      status: "success",
      error: null,
      fieldErrors: {},
      snapshot: preset,
    });
  });

  it.each(tasks)(
    "times out %s after 15 seconds even if the gateway ignores abort",
    async (task) => {
      vi.useFakeTimers();
      const late = createDeferred<unknown>();
      const { result, gateway } = setup({ [task]: [{ kind: "late", response: late.promise }] });
      let pending!: Promise<void>;
      act(() => {
        pending = invoke(result.current, task);
      });
      await act(async () => {
        await vi.advanceTimersByTimeAsync(14_999);
      });
      expect(result.current.isBusy).toBe(true);
      await act(async () => {
        await vi.advanceTimersByTimeAsync(1);
        await pending;
      });
      expect(result.current).toMatchObject({
        status: "error",
        isBusy: false,
        error: "Yêu cầu quá thời gian chờ. Vui lòng thử lại.",
        result: null,
      });
      const abortSignal =
        task === "exchange"
          ? gateway.exchange.mock.calls[0][1]
          : gateway.generatePrivateValues.mock.calls[0][1];
      expect(abortSignal.aborted).toBe(true);
      await act(async () => {
        await invoke(result.current, task);
      });
      expect(result.current.status).toBe("success");
      await act(async () => {
        late.resolve(task === "exchange" ? createDhPresetResult() : createDhRandomValues());
        await Promise.resolve();
      });
      expect(result.current.status).toBe("success");
      expect(vi.getTimerCount()).toBe(0);
    },
  );

  it("handles a timeout when the gateway rejects on abort", async () => {
    vi.useFakeTimers();
    const { result } = setup({ exchange: [{ kind: "timeout" }] });
    let pending!: Promise<void>;
    act(() => {
      pending = result.current.exchange();
    });
    await act(async () => {
      await vi.advanceTimersByTimeAsync(15_000);
      await pending;
    });
    expect(result.current.error).toBe("Yêu cầu quá thời gian chờ. Vui lòng thử lại.");
  });

  it("preserves drafts on deactivation, aborts, and does not auto-run on return", async () => {
    const deferred = createDeferred<unknown>();
    const { result, rerender, gateway } = setup({
      random: [{ kind: "late", response: deferred.promise }],
    });
    act(() => result.current.setParameter("privateA", "7"));
    let pending!: Promise<void>;
    act(() => {
      pending = result.current.generatePrivateValues();
    });
    rerender({ gateway, active: false });
    expect(gateway.generatePrivateValues.mock.calls[0][1].aborted).toBe(true);
    await act(async () => {
      deferred.resolve(createDhRandomValues());
      await pending;
    });
    await act(async () => {
      await result.current.exchange();
    });
    expect(gateway.exchange).not.toHaveBeenCalled();
    expect(result.current).toMatchObject({
      status: "idle",
      draft: { ...preset, privateA: "7" },
      snapshot: null,
    });
    rerender({ gateway, active: true });
    expect(gateway.generatePrivateValues).toHaveBeenCalledTimes(1);
    expect(result.current.status).toBe("idle");
  });

  it("invalidates the old gateway and clears loading when the injected gateway changes", async () => {
    const deferred = createDeferred<unknown>();
    const { result, rerender, gateway } = setup({
      exchange: [{ kind: "late", response: deferred.promise }],
    });
    let pending!: Promise<void>;
    act(() => {
      pending = result.current.exchange();
    });
    const next = createDiffieHellmanGateway();
    rerender({ gateway: next, active: true });
    expect(result.current.status).toBe("idle");
    expect(gateway.exchange.mock.calls[0][1].aborted).toBe(true);
    await act(async () => {
      await result.current.exchange();
    });
    await act(async () => {
      deferred.resolve(null);
      await pending;
    });
    expect(result.current.status).toBe("success");
    rerender({ gateway: null, active: true });
    await act(async () => {
      await result.current.exchange();
    });
    expect(result.current).toMatchObject({ hasGateway: false, status: "idle", result: null });
  });

  it.each(tasks)("aborts %s on unmount and removes its timeout", async (task) => {
    vi.useFakeTimers();
    const deferred = createDeferred<unknown>();
    const { result, unmount, gateway } = setup({
      [task]: [{ kind: "late", response: deferred.promise }],
    });
    let pending!: Promise<void>;
    act(() => {
      pending = invoke(result.current, task);
    });
    const abortSignal =
      task === "exchange"
        ? gateway.exchange.mock.calls[0][1]
        : gateway.generatePrivateValues.mock.calls[0][1];
    unmount();
    expect(abortSignal.aborted).toBe(true);
    expect(vi.getTimerCount()).toBe(0);
    deferred.reject(new Error("late unmounted failure"));
    await pending;
  });

  it("shows validated business errors, clears them on edit, and retries explicitly", async () => {
    const { result } = setup({ random: [{ kind: "error" }] });
    await act(async () => {
      await result.current.generatePrivateValues();
    });
    expect(result.current).toMatchObject({
      status: "error",
      draft: preset,
      error: "Lỗi thử nghiệm <Backend> & yêu cầu thử lại.",
      fieldErrors: { alpha: "Lỗi thử nghiệm <Backend> & yêu cầu thử lại." },
    });
    act(() => result.current.setParameter("alpha", "5"));
    expect(result.current).toMatchObject({ status: "idle", error: null, fieldErrors: {} });
    await act(async () => {
      await result.current.generatePrivateValues();
    });
    expect(result.current.status).toBe("success");
  });

  it("does not display untrusted exception text or attach an unknown field", async () => {
    const business = Object.assign(
      new DiffieHellmanGatewayError("Business message", "INVALID_REQUEST"),
      {
        field: "unknown_field",
      },
    );
    const { result } = setup({
      exchange: [
        { kind: "error", error: new TypeError("sensitive exception") },
        { kind: "error", error: business },
      ],
    });
    await act(async () => {
      await result.current.exchange();
    });
    expect(result.current.error).toBe("Không thể xử lý yêu cầu. Vui lòng thử lại.");
    await act(async () => {
      await result.current.exchange();
    });
    expect(result.current.error).toBe("Business message");
    expect(result.current.fieldErrors).toEqual({});
  });

  const invalidExchanges: [string, () => unknown][] = [
    ["null", () => null],
    ["wrong q", () => ({ ...createDhPresetResult(), q: "47" })],
    ["numeric output", () => ({ ...createDhPresetResult(), publicA: 8 })],
    ["noncanonical output", () => ({ ...createDhPresetResult(), publicA: "08" })],
    ["mismatch", () => ({ ...createDhPresetResult(), sharedB: "3" })],
    ["matched false", () => ({ ...createDhPresetResult(), matched: false })],
    ["missing traces", () => createDhPresetResult(false)],
    [
      "truncated trace",
      () => {
        const value = createDhPresetResult();
        value.traces!.publicA.steps.pop();
        return value;
      },
    ],
    [
      "wrong exponent",
      () => {
        const value = createDhPresetResult();
        value.traces!.sharedB.exponent = "6";
        return value;
      },
    ],
    [
      "wrong exponent prefix",
      () => {
        const value = createDhPresetResult();
        value.traces!.publicA.steps[1].exponentPrefix = "2";
        return value;
      },
    ],
  ];

  it.each(invalidExchanges)(
    "rejects %s without committing any snapshot or output",
    async (_, value) => {
      const { result } = setup({ exchange: [{ kind: "invalid-schema", value: value() }] });
      await act(async () => {
        await result.current.exchange();
      });
      expect(result.current).toMatchObject({
        status: "error",
        error: "Dữ liệu phản hồi không hợp lệ. Vui lòng thử lại.",
        snapshot: null,
        result: null,
      });
    },
  );

  it.each([
    null,
    { ...createDhRandomValues(), alpha: "7" },
    { ...createDhRandomValues(), privateA: "1" },
    { ...createDhRandomValues(), privateB: "22" },
  ])("rejects invalid random values %j and preserves the draft", async (value) => {
    const { result } = setup({ random: [{ kind: "invalid-schema", value }] });
    await act(async () => {
      await result.current.generatePrivateValues();
    });
    expect(result.current).toMatchObject({
      status: "error",
      draft: preset,
      result: null,
      snapshot: null,
    });
  });

  it("reset and clearResults remove outputs without running or losing the wrong draft", async () => {
    const { result, gateway } = setup();
    await act(async () => {
      await result.current.generatePrivateValues();
    });
    await act(async () => {
      await result.current.exchange();
    });
    act(() => result.current.clearResults());
    expect(result.current).toMatchObject({
      draft: createDhRandomValues(),
      status: "idle",
      snapshot: null,
      result: null,
    });
    act(() => result.current.resetAll());
    expect(result.current.draft).toEqual(empty);
    expect(result.current.resetVersion).toBe(2);
    expect(gateway.exchange).toHaveBeenCalledTimes(1);
    expect(gateway.generatePrivateValues).toHaveBeenCalledTimes(1);
  });
});
